customer/urls.py
from django.urls import path 

from . import views

urlpatterns = [ 

    path('cust-login',views.login),
    path('signup',views.signup),
    path('forgot',views.forgot)
]

mobilemart/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('shopadmin/',include('shop_admin.urls'))

]

shop_admin/urls.py
from django.urls import path 

from . import views

app_name='sadmin'

urlpatterns = [ 
   
    path('add',views.add,name='addp'),
    path('home',views.home,name='home'),
    path('login',views.login,name='login'),
    path('manage',views.manage,name='maange'),
    path('stock',views.stock,name='stock'),
    path('update',views.update,name='upd'),

]

customer/models.py
from django.db import models

# Create your models here.

shop_admin/models.py
from django.db import models

# Create your models here.

customer/views.py
from django.shortcuts import render

# Create your views here.


def login(request):
    return render(request,'customer/login.html')

def signup(request):
    return render(request,'customer/signup.html')


def forgot(request):
    return render(request,'customer/forgot_pass.html')

shop_admin/views.py
from django.shortcuts import render

# Create your views here.


def add(request):
    return render(request,'shop_admin/add_products.html')

def home(request):
    return render(request,'shop_admin/home.html')

def login(request):
    return render(request,'shop_admin/login.html')

def manage(request):
    return render(request,'shop_admin/manage_user.html')

def stock(request):
    return render(request,'shop_admin/stock.html')

def update(request):
    return render(request,'shop_admin/update.html')

customer/templates/customer/forgot_pass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    forgot password
    
</body>
</html>

customer/templates/customer/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    customer login
</body>
</html>

customer/templates/customer/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    signup page
</body>
</html>

shop_admin/templates/shop_admin/add_products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    products adding page
    
</body>
</html>

shop_admin/templates/shop_admin/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ol>
        <li>manage user</li>
        <li>add products</li>
        <li>update products</li>
        <li>stock management</li>
    </ol>
</body>
</html>

shop_admin/templates/shop_admin/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    login page

    <br>
    <img src="{% static 'images/fede.jpeg' %}" alt="" height="100px">
    <a href="{% url 'sadmin:home' %}"><b>login</b></a>

</body>
</html>

shop_admin/templates/shop_admin/manage_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    user management page
    
</body>
</html>

shop_admin/templates/shop_admin/stock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    stock management page
</body>
</html>

shop_admin/templates/shop_admin/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    updation page
</body>
</html>